<script lang="ts">
	import type { Disk } from '$types/read-from-opt.js';
	import { Method, Preview, type BootPath } from '$types/installation/partitioning/partitioning.types';
	import { partitionMethod } from '$lib/stores/informationStore';
	import { onMount } from 'svelte';
	import TwoSide from '$lib/components/layouts/TwoSide.svelte';
	import GlowingText from '$lib/components/ui/GlowingText.svelte';
	import DiskPreview from '$lib/components/DiskPreview.svelte';
	import PreviewButton from './components/PreviewButton.svelte';
	import Card from './components/Card.svelte';
	import Navigation from '$lib/components/Navigation.svelte';
	import SelectComponent from '$lib/components/SelectComponent.svelte';
	import { getDiskAfter } from './utils.js';
	import { prettySize } from '$lib/essentials.js';
	import { getSystemInfo } from '$lib/utils/read_utils.js';
	import { commands, type Storage } from '$types/commands';

	let disks = $state<Disk[] | null>(null);
	let selectedDisk = $state<Disk | null>(null);
	let selectedMethod = $state<BootPath | null>(null);
	let showSingleBootWarning = $state(false);
	let warningPosition = $state({ x: 0, y: 0 });
	let diskAfter = $state<Disk | null>(null);
	let selectedPreview = $state(Preview.BEFORE);
	let partitionTable = $state('gpt');

	let disableNext = $derived(selectedMethod === null);
	let showAfter = $derived(selectedMethod === 'single');

	const selectMethod = (method: BootPath) => {
		selectedMethod = method;
		$partitionMethod = method;

		if (method === Method.SINGLE) {
			selectedPreview = Preview.AFTER;
		} else {
			selectedPreview = Preview.BEFORE;
		}
	};

	const handleSetMethod = async () => {
		if (selectedDisk && selectedMethod) {
			let storage_skel: Storage;
			// TODO: CHECK THE BEHAVIOR OF ORIGINAL SECTOR

			switch (selectedMethod) {
				case Method.SINGLE:
					storage_skel = {
						originalSector: null,
						diskPath: selectedDisk.diskPath,
						partitionTable: selectedDisk.label === 'unknown' ? 'gpt' : selectedDisk.label,
						newPartitionTable: true,
						layoutChanged: false,
						autogenerated: true,
						autogeneratedMode: selectedMethod,
						installMethod: selectedMethod,
						partitions: null
					};
					break;

				case Method.DUAL:
					storage_skel = {
						originalSector: null,
						diskPath: selectedDisk.diskPath,
						partitionTable: selectedDisk.label === 'unknown' ? 'gpt' : selectedDisk.label,
						newPartitionTable: false,
						layoutChanged: false,
						autogenerated: true,
						autogeneratedMode: selectedMethod,
						installMethod: selectedMethod,
						partitions: null
					};
					break;

				case Method.MANUAL:
					storage_skel = {
						originalSector: null,
						diskPath: selectedDisk.diskPath,
						partitionTable: selectedDisk.label === 'unknown' ? 'gpt' : selectedDisk.label,
						newPartitionTable: false,
						layoutChanged: false,
						autogenerated: false,
						autogeneratedMode: '',
						installMethod: selectedMethod,
						partitions: null
					};
					break;
				default:
					return;
			}

			await commands.blueprintSetStorage(JSON.stringify(storage_skel));
		}
	};

	const showWarning = (
		event: MouseEvent & {
			currentTarget: EventTarget & HTMLElement;
		}
	) => {
		showSingleBootWarning = true;
		warningPosition = { x: event.clientX, y: event.clientY };
	};

	const hideWarning = () => {
		showSingleBootWarning = false;
	};

	$effect(() => {
		if (selectedDisk && partitionTable) {
			diskAfter = getDiskAfter(selectedDisk, 'ext4', partitionTable, 0);

			selectedPreview = Preview.BEFORE;
			selectedMethod = null;
		}
	});

	onMount(async () => {
		const data = await getSystemInfo();

		if (data) {
			disks = data.disk;
		}

		partitionTable = selectedDisk?.label ?? 'gpt';
	});
</script>

<TwoSide>
	{#snippet left()}
		<div class="mx-[35px] space-y-[15px]">
			<h1 class="font-archivo font-semibold text-[28px]">
				Choose your <span class="text-green-tealinux">disk</span> and
				<br />
				<span class="text-green-tealinux">installation method</span>
			</h1>
			<p class="font-jakarta text-sm font-extralight">
				Select the disk where you want to install the system and pick your preferred installation
				method, whether manual for some control or automatic for ease.
			</p>
		</div>
	{/snippet}

	{#snippet right()}
		<div
			class="flex flex-col p-4 space-y-[15px] mb-[15px] bg-black/30 border-[0.5px] border-gray-900 rounded-[10px] font-jakarta"
		>
			<GlowingText size="[11]" text="Disk" />

			<div class="flex flex-col">
				<SelectComponent
					options={disks}
					bind:value={selectedDisk}
					onselect={(disk) => {
						selectedMethod = null;
						selectedDisk = disk;
					}}
					defaultText="Select a destination disk"
					notFoundText="No storage device detected"
					displayField="diskPath"
					sizeField="size"
					formatter={prettySize}
				/>
			</div>
			<!-- Disk selection -->
			<GlowingText size="[11]" text="Methods" />
			<!-- Partitioning Methods -->
			<div class="flex flex-start gap-[15px] p-2.5 w-full">
				<!-- Single Boot Card -->
				<Card
					disable={selectedDisk === null}
					method={Method.SINGLE}
					onclick={() => selectMethod(Method.SINGLE)}
					onmouseenter={showWarning}
					onmouseleave={hideWarning}
					title="Single Boot"
					description="Choose this if you only want TealinuxOS to be the only operating system in your computer"
					{selectedMethod}
				></Card>

				<!-- Double Boot Card -->
				<Card
					disable={selectedDisk === null}
					method={Method.DUAL}
					onclick={() => selectMethod(Method.DUAL)}
					title="Dual Boot"
					description="Choose this if you want TealinuxOS to be installed alongside other operating system"
					{selectedMethod}
				></Card>

				<!-- Manual Partition Card -->
				<Card
					disable={selectedDisk === null}
					method={Method.MANUAL}
					onclick={() => selectMethod(Method.MANUAL)}
					title="Manual Partitioning"
					description="Do. whatever. you. want."
					{selectedMethod}
				></Card>
			</div>

			<GlowingText size="[11]" text="Disk Preview" />

			<!-- Add this section after the partitioning tools section -->
			{#key selectedDisk}
				<div
					class={`flex flex-col p-[15px] gap-2.5 self-stretch rounded-[10.267px] border border-[#3C6350] bg-[#101010] ${
						!selectedDisk ? 'grayscale' : ''
					}`}
				>
					{#if selectedDisk}
						<div class="flex flex-row space-x-2">
							<PreviewButton
								title={Preview.BEFORE}
								selected={selectedPreview === Preview.BEFORE}
								onclick={() => (selectedPreview = Preview.BEFORE)}
							/>
							{#if selectedMethod && showAfter}
								<PreviewButton
									title={Preview.AFTER}
									selected={selectedPreview === Preview.AFTER}
									onclick={() => (selectedPreview = Preview.AFTER)}
								/>
							{/if}
						</div>
						<div class="space-y-2.5 w-full">
							<div class="space-y-2.5">
								{#if selectedPreview === Preview.BEFORE}
									<DiskPreview disk={selectedDisk} />
								{:else if diskAfter}
									<DiskPreview disk={diskAfter} />
								{/if}
							</div>
						</div>
					{:else}
						<div
							class="text-[#E4E4E4] font-jakarta text-[9.46px] font-medium leading-[17.659px] text-center py-4"
						>
							Select a disk to see preview
						</div>
					{/if}
				</div>
			{/key}
		</div>
	{/snippet}
</TwoSide>

{#if selectedDisk && showSingleBootWarning}
	<div
		class="absolute bg-[#3C6350] text-white p-3 rounded-lg shadow-lg z-50 max-w-[200px]"
		style="left: {warningPosition.x}px; top: {warningPosition.y + 20}px"
	>
		<p class="text-xs">
			Warning: This will erase all existing data on the selected disk. Make sure to backup any
			important files.
		</p>
	</div>
{/if}

<Navigation
	currentStep={3}
	currentTitle="Partitioning"
	prevPath="/installation/localization"
	nextPath="/installation/partitioning/{selectedMethod as BootPath}"
	nextAction={handleSetMethod}
	{disableNext}
/>
