
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getReadJson() : Promise<string> {
    return await TAURI_INVOKE("get_read_json");
},
async setReadJson() : Promise<void> {
    await TAURI_INVOKE("set_read_json");
},
async setEmptyBlueprint() : Promise<void> {
    await TAURI_INVOKE("set_empty_blueprint");
},
async getFilesystemJson() : Promise<string> {
    return await TAURI_INVOKE("get_filesystem_json");
},
async getReadFromOpt() : Promise<string> {
    return await TAURI_INVOKE("get_read_from_opt");
},
async getBlueprintFromOpt() : Promise<string> {
    return await TAURI_INVOKE("get_blueprint_from_opt");
},
async readBlueprint() : Promise<void> {
    await TAURI_INVOKE("read_blueprint");
},
async getOtherOsJson() : Promise<string> {
    return await TAURI_INVOKE("get_other_os_json");
},
async blueprintSetLocale(locale: string) : Promise<void> {
    await TAURI_INVOKE("blueprint_set_locale", { locale });
},
async getLocaleJson() : Promise<string> {
    return await TAURI_INVOKE("get_locale_json");
},
async blueprintSetTimezone(region: string, city: string) : Promise<void> {
    await TAURI_INVOKE("blueprint_set_timezone", { region, city });
},
async getTimezoneJson() : Promise<string> {
    return await TAURI_INVOKE("get_timezone_json");
},
async blueprintSetAccount(fullname: string, username: string, hostname: string, password: string, autologin: boolean) : Promise<void> {
    await TAURI_INVOKE("blueprint_set_account", { fullname, username, hostname, password, autologin });
},
async blueprintSetBootloader(bootloader: string) : Promise<void> {
    await TAURI_INVOKE("blueprint_set_bootloader", { bootloader });
},
async blueprintSetKeyboard(layout: string, variant: string | null) : Promise<void> {
    await TAURI_INVOKE("blueprint_set_keyboard", { layout, variant });
},
async getKeyboardJson() : Promise<string> {
    return await TAURI_INVOKE("get_keyboard_json");
},
async setCosmicKeymap(live: boolean, layout: string, variant: string | null) : Promise<void> {
    await TAURI_INVOKE("set_cosmic_keymap", { live, layout, variant });
},
async getDiskListsKeyVal() : Promise<string> {
    return await TAURI_INVOKE("get_disk_lists_key_val");
},
async getDiskListsKeyValWithOtherosCheck() : Promise<string> {
    return await TAURI_INVOKE("get_disk_lists_key_val_with_otheros_check");
},
async autogenPartitionSelectDisk(blkname: string, mode: string, partitionTable: string, fs: string, useSwap: boolean, start: bigint | null, end: bigint | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("autogen_partition_select_disk", { blkname, mode, partitionTable, fs, useSwap, start, end }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async blueprintSetStorage(storage: string) : Promise<void> {
    await TAURI_INVOKE("blueprint_set_storage", { storage });
},
async readRefreshDisk() : Promise<void> {
    await TAURI_INVOKE("read_refresh_disk");
},
async startInstall() : Promise<void> {
    await TAURI_INVOKE("start_install");
},
async isOnline() : Promise<boolean> {
    return await TAURI_INVOKE("is_online");
},
async printJson() : Promise<void> {
    await TAURI_INVOKE("print_json");
},
async testPartitioning() : Promise<void> {
    await TAURI_INVOKE("test_partitioning");
},
async reboot() : Promise<void> {
    await TAURI_INVOKE("reboot");
},
async spawnGparted() : Promise<void> {
    await TAURI_INVOKE("spawn_gparted");
},
async spawnTerminal() : Promise<void> {
    await TAURI_INVOKE("spawn_terminal");
},
async openWebsite() : Promise<void> {
    await TAURI_INVOKE("open_website");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Account = { fullname: string; username: string; hostname: string; password: string; autologin: boolean }
export type BluePrint = { account: Account | null; locale: Locale | null; timezone: Timezone | null; storage: Storage | null; bootloader: Bootloader | null; keyboard: Keyboard | null }
export type Bootloader = { firmwareType: FirmwareKind; path: string | null }
export type FirmwareKind = "UEFI" | "BIOS"
export type Keyboard = { layout: string | null; variant: string | null }
export type Locale = { main: string }
export type MethodKind = "single" | "dual" | "manual"
export type OriginalSector = { start: bigint | null; end: bigint | null }
export type Partition = { number: bigint; diskPath: string | null; path: string | null; mountpoint: string | null; filesystem: string | null; label: string | null; format: boolean; start: bigint; end: bigint; size: bigint; flags: string[] | null }
export type Storage = { originalSector: OriginalSector | null; diskPath: string | null; partitionTable: string | null; newPartitionTable: boolean; layoutChanged: boolean; autogenerated: boolean; autogeneratedMode: string; installMethod: MethodKind; partitions: Partition[] | null }
export type Timezone = { region: string; city: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
